libc/uClibc: fix building on system with recent glibc
While trying to build a toolchain with ct-ng 1.5.0,
arm-unknown-linux-uclibcgnueabi target,
I get the following error:

[INFO ]  Installing C library headers
[EXTRA]    Copying sources to build dir
[EXTRA]    Applying configuration
[EXTRA]    Building headers
[EXTRA]    Installing headers
[ERROR]    extra/scripts/unifdef.c:209: error: conflicting types for 'getline'
[ERROR]    make[2]: *** [extra/scripts/unifdef] Error 1
[ERROR]    Build failed in step 'Installing C library headers'

The following patch solves the problem.
(It's a backport of this uClibc commit:
http://git.uclibc.org/uClibc/commit/?id=49e81cada73616864b9b31df0aeb6961c30f5a6e
)

[--SNIP from another mail--]
AFAIK this is a problem since glibc 2.10.
(transplanted from 1ba79f2126df8bd89120899a58f2d0bcc2e9c771)

--HG--
branch : 1.5
extra : transplant_source : %1B%A7%9F%21%26%DF%8B%D8%91%20%89%9AX%F2%D0%BC%C2%E9%C7q